services:
  - type: web
    name: summermedical-backend
    env: node
    buildCommand: cd summermedical-backend && npm install
    startCommand: cd summermedical-backend && node index.js
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3606
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: summer_user
      - key: DB_PASSWORD
        value: root
      - key: DB_NAME
        value: summer_medical
      - key: CORS_ORIGIN
        value: https://Louizyyye.github.com
      - key: PORT
         value: 3000
      - key: DB_HOST
         value: dpg-d3pteifdiees73c4juf0-a
      - key: DB_USER
         value: summer_medical_user
      - key: DB_PASS
          value: uqx2gVQUUZV5RSWV8s1sRuBxqStRIBmH
      - key: DB_NAME
           value: summer_medical
      - key: AT_API_KEY
           value: your-africastalking-api-key
      - key: AT_USERNAME
          value: your-africastalking-username


- name: summer_medical
  plan: free
